name: ci-bowfolios

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - uses: meteorengineer/setup-meteor@v1
      - run: meteor npm install
      - run: meteor npm run lint
      - run: meteor npm run testcafe-ci
